main_whole.py文件始终有错误